# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_MEDIATEK)  += mt6983.dtb
dtbo-$(CONFIG_ARCH_MEDIATEK) += oplus6983_22823.dtbo

always-y        := $(dtb-y) $(dtbo-y)
subdir-y        := $(dts-dirs)
clean-files     := *.dtb *.dtbo
