# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2022 Oplus. All rights reserved.

obj-$(CONFIG_OPLUS_FEATURE_CMDLINE)     += cmdline_parser/
obj-$(CONFIG_OPLUS_FEATURE_OPROJECT)    += oplus_project/
